#Config/hyperparameters.yaml
import os
import yaml

# 获取当前文件目录，并拼接 Config 文件路径
config_path = os.path.join(os.path.dirname(__file__), "Config/hyperparameters.yaml")

# 读取 YAML 配置文件
with open(config_path, "r", encoding="utf-8") as f:
    config = yaml.safe_load(f)

print(config)  # 确保能正确读取 YAML 配置
# 训练参数
training:
  total_episodes: 1000
  batch_size: 64
  gamma: 0.99          # 折扣因子
  lr: 0.001            # 学习率
  epsilon_start: 1.0   # 初始探索率
  epsilon_end: 0.01
  epsilon_decay: 0.995
  target_update: 10    # 目标网络更新频率
  buffer_size: 10000   # 经验回放缓冲大小

# 模型参数
model:
  input_dim: 4         # 输入维度
  hidden_dim: 128      # 隐藏层维度
  output_dim: 2        # 动作空间维度

# 日志参数
logging:
  log_dir: ./logs
  log_interval: 20     # 记录间隔（episodes）